name: Auto Liker

on:
  workflow_dispatch:
    inputs:
      react:
        type: choice
        description: 'Select any React'
        required: true
        default: 'LIKE'
        options: ['LIKE', 'LOVE', 'CARE', 'HAHA', 'WOW', 'SAD', 'ANGRY']
      post_link:
        description: 'Enter a Post Link'
        required: true
      amount:
        description: 'Enter react amount'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run main.py
      run: python main.py "${{ github.event.inputs.post_link }}" "${{ github.event.inputs.amount }}" "${{ github.event.inputs.react }}"
      shell: cmd
